INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (1, 'Geographic', 0, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (2, 'Polygon properties', 34, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (3, 'WKT', 34, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (4, 'Numeric Functions', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (5, 'Plugins', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (6, 'MBR', 34, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (7, 'Control flow functions', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (8, 'Transactions', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (9, 'Help Metadata', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (10, 'Account Management', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (11, 'Point properties', 34, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (12, 'Encryption Functions', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (13, 'LineString properties', 34, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (14, 'Miscellaneous Functions', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (15, 'Logical operators', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (16, 'Functions and Modifiers for Use with GROUP BY', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (17, 'Information Functions', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (18, 'Comparison operators', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (19, 'Bit Functions', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (20, 'Table Maintenance', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (21, 'User-Defined Functions', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (22, 'Data Types', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (23, 'Compound Statements', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (24, 'Geometry constructors', 34, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (25, 'GeometryCollection properties', 1, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (26, 'Administration', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (27, 'Data Manipulation', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (28, 'Utility', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (29, 'Language Structure', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (30, 'Geometry relations', 34, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (31, 'Date and Time Functions', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (32, 'WKB', 34, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (33, 'Procedures', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (34, 'Geographic Features', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (35, 'Contents', 0, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (36, 'Geometry properties', 34, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (37, 'String Functions', 38, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (38, 'Functions', 35, '');
INSERT INTO mysql.help_category (help_category_id, name, parent_category_id, url) VALUES (39, 'Data Definition', 35, '');